### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [loganlennox/hubbot#1]
Hello @loganlennox, Im a Graphic Designer that likes to contribute to open source projects, I would like to know if you need a logo for you project? I would like to work with you. 

What can you tell me more about the Hubbot?

If you want a logo just tell me what you want, and I will do it.

Best Regards!

**Comment by loganlennox** [comment]
Hey @zuurw, although I'm very thankful for your offer, a logo design for this particular project will not be required as this need has already been met. Thank you again for offering your services, it is very much appreciated.

**Comment by zuurw** [comment]
Hi @loganlennox, ok, I saw in your profile that you have other projects, do you need a logo for them?

**Comment by zuurw** [comment]
My work is for free.

**Comment by loganlennox** [comment]
For the other projects, it is not necessary for that service to be utilized at this point in time. However, I'll be sure to contact you if this is a requirement in a future project. Thank you so much for your offer, I'm sure we'll speak again in the near future.
